#include <additions/configuration>
#include <additions/colors>

Create3DTexts(){
	CreateDynamic3DTextLabel("Наш адрес в интернете "SUNBURN""SITE_LINK"\n"WHITE"Страничка [В]Контакте - "SUNBURN""VK_LINK""WHITE"\nНаш сервер:\nOrioN Server №1 IP:"IP_SERVER"",-1,-1994.7456,137.8349,30.4119,100.0);
	CreateDynamic3DTextLabel("* * * "LIGHT_STEEL_BLUE"П О М О Щ Ь"WHITE" * * *",-1,-1977.4960,133.5098,27.6940,50.0);
	CreateDynamic3DTextLabel("Тут можно изменить место возрождения\n"WHITE"Используй: /changerespawn",C_SUNBURN,-1976.5925,141.8520,27.6875,50.0);
}