#define WHITE "{ffffff}"
#define GREEN "{249900}"
#define BLUE "{3399cc}"
#define GREY "{afafaf}"
#define RED "{fb6146}"
#define YELLOW "{ffff00}"
#define CURIOUS_BLUE "{3399cc}"
#define YELLOW_GREEN "{9acd32}"
#define SUNBURN "{d7b481}"
#define LIGHT_STEEL_BLUE "{a9c4e4}"

#define C_GREY 0xAFAFAFAA
#define C_YELLOW_GREEN 0x9ACD32AA
#define C_RED 0xFB6146AA
#define C_SUNBURN 0xD7B481AA
#define C_LIGHT_STEEL_BLUE 0xA9C4E4AA
#define C_PURPLE 0xC2A2DAAA