#undef MAX_PLAYERS
#define MAX_PLAYERS 100
#define MAX_LICENSES 5

#define SITE_LINK "www.orio-n.com"
//#define SITE_MAIL "admin@d1maz.ru"
#define SITE_MAIL "support@orio-n.com"
#define IP_SERVER "127.0.0.1:7777"
#define VK_LINK "vk.com/orionservers"

#define LICENSE_DRIVING 0//лицензия на вождение транспорта
#define LICENSE_WEAPON 1//лицензия на ношение оружия
#define LICENSE_FLYING 2//лицензия на управление воздушным транспортом
#define LICENSE_MOTORCYCLE 3//лицензия на вождение мотоциклом
#define LICENSE_BOATING 4//лицензия на управление водным транспортом